apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-app
  namespace: staging
spec:
  interval: 1m
  path: "./apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name : flux-system
    namespace : flux-system
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/base

