apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-app
spec:
  interval: 1m
  path: "./apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name : flux-system
    namespace : flux-system
