apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: logging
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    # SingleBinary configuration
    singleBinary:
      enabled: true  # Explicitly enable
      replicas: 1    # Single replica for development
      persistence:
        enabled: false  # Disable for demo, enable for production
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
    # Explicitly disable other modes
    simpleScalable:
      enabled: false  # Must be explicitly disabled
      replicas: 0     # Ensure zero replicas