apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: logging
  install:
    remediation:
      retries: 3
    createNamespace: true
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      limits_config:
        allow_structured_metadata: true
        retention_period: 24h
        volume_enabled: true
      # https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
        enabled: true
      ruler:
        enable_api: true
    # SingleBinary configuration
    deploymentMode: SingleBinary
    singleBinary:
      enabled: true  # Explicitly enable
      replicas: 1    # Single replica for development
      persistence:
        enabled: false  # Disable for demo, enable for production
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 512Mi
    # Explicitly disable other modes
    simpleScalable:
      enabled: false  # Must be explicitly disabled
      replicas: 0     # Ensure zero replicas
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
